{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Optimization"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sn\n",
    "import platypus"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/jhkwakkel/miniconda3/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__\n",
      "  return f(*args, **kwds)\n"
     ]
    }
   ],
   "source": [
    "import sys\n",
    "\n",
    "sys.path.append('./final assignment/')\n",
    "\n",
    "import dike_model_function\n",
    "import dike_model_optimization\n",
    "import dike_model_simulation\n",
    "import problem_formulation"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<Logger EMA (DEBUG)>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from ema_workbench import Policy, perform_experiments\n",
    "from ema_workbench import ema_logging, MultiprocessingEvaluator\n",
    "import ema_workbench\n",
    "ema_logging.log_to_stderr(ema_logging.INFO)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.2\n"
     ]
    }
   ],
   "source": [
    "print(ema_workbench.__version__)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: './data/dikeIjssel.xlsx'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-6-cadadaa1e3a8>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mproblem_formulation\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_model_for_problem_formulation\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m1\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/Documents/workspace/epa1361_open/final assignment/problem_formulation.py\u001b[0m in \u001b[0;36mget_model_for_problem_formulation\u001b[0;34m(problem_formulation_id)\u001b[0m\n\u001b[1;32m     23\u001b[0m     '''\n\u001b[1;32m     24\u001b[0m     \u001b[0;31m# Load the model:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 25\u001b[0;31m     \u001b[0mfunction\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mDikeNetwork\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     26\u001b[0m     \u001b[0;31m# workbench model:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     27\u001b[0m     \u001b[0mdike_model\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mModel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'dikesnet'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mfunction\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mfunction\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Documents/workspace/epa1361_open/final assignment/dike_model_function.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     26\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m__init__\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     27\u001b[0m         \u001b[0;31m# load network\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 28\u001b[0;31m         \u001b[0mG\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdike_list\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdike_branch\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfuns_generate_network\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget_network\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     29\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     30\u001b[0m         \u001b[0;31m# Load hydrological statistics:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/Documents/workspace/epa1361_open/final assignment/funs_generate_network.py\u001b[0m in \u001b[0;36mget_network\u001b[0;34m()\u001b[0m\n\u001b[1;32m     16\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     17\u001b[0m     \u001b[0;31m# Upload dike info\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 18\u001b[0;31m     \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_excel\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'./data/dikeIjssel.xlsx'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdtype\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mobject\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     19\u001b[0m     \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mset_index\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'NodeName'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     20\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.6/site-packages/pandas/util/_decorators.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    175\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    176\u001b[0m                     \u001b[0mkwargs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mnew_arg_name\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnew_arg_value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 177\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    178\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    179\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0m_deprecate_kwarg\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.6/site-packages/pandas/util/_decorators.py\u001b[0m in \u001b[0;36mwrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    175\u001b[0m                 \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    176\u001b[0m                     \u001b[0mkwargs\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mnew_arg_name\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mnew_arg_value\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 177\u001b[0;31m             \u001b[0;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0margs\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    178\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mwrapper\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    179\u001b[0m     \u001b[0;32mreturn\u001b[0m \u001b[0m_deprecate_kwarg\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/miniconda3/lib/python3.6/site-packages/pandas/io/excel.py\u001b[0m in \u001b[0;36mread_excel\u001b[0;34m(io, sheet_name, header, names, index_col, usecols, squeeze, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, parse_dates, date_parser, thousands, comment, skipfooter, convert_float, **kwds)\u001b[0m\n\u001b[1;32m    305\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    306\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mio\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mExcelFile\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 307\u001b[0;31m         \u001b[0mio\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mExcelFile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mio\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mengine\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mengine\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    308\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    309\u001b[0m     return io.parse(\n",
      "\u001b[0;32m~/miniconda3/lib/python3.6/site-packages/pandas/io/excel.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, io, **kwds)\u001b[0m\n\u001b[1;32m    392\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbook\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mxlrd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mopen_workbook\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfile_contents\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mdata\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    393\u001b[0m         \u001b[0;32melif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_io\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mcompat\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstring_types\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 394\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbook\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mxlrd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mopen_workbook\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_io\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    395\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    396\u001b[0m             raise ValueError('Must explicitly set engine if not passing in'\n",
      "\u001b[0;32m~/miniconda3/lib/python3.6/site-packages/xlrd/__init__.py\u001b[0m in \u001b[0;36mopen_workbook\u001b[0;34m(filename, logfile, verbosity, use_mmap, file_contents, encoding_override, formatting_info, on_demand, ragged_rows)\u001b[0m\n\u001b[1;32m    114\u001b[0m         \u001b[0mpeek\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfile_contents\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0mpeeksz\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    115\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 116\u001b[0;31m         \u001b[0;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilename\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"rb\"\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    117\u001b[0m             \u001b[0mpeek\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpeeksz\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    118\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mpeek\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34mb\"PK\\x03\\x04\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;31m# a ZIP file\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: './data/dikeIjssel.xlsx'"
     ]
    }
   ],
   "source": [
    "model = problem_formulation.get_model_for_problem_formulation(1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[MainProcess/INFO] pool started\n",
      "[MainProcess/INFO] generation 0: 0/250 nfe\n",
      "[MainProcess/INFO] performing 1 scenarios * 100 policies * 1 model(s) = 100 experiments\n",
      "[SpawnPoolWorker-1/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-8/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-6/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-2/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-3/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-5/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-4/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-7/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-9/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-10/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-11/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-12/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-13/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-14/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-15/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-16/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-17/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-18/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-19/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-20/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-21/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-22/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-23/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-24/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-25/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-26/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-27/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-28/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-29/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-30/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-31/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-32/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-33/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-34/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-35/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-36/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-37/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-38/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-39/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-40/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-41/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-42/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-43/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-44/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-45/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-46/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-47/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-48/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-49/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-50/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-51/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-52/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-53/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-54/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-55/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-56/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-57/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-58/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-59/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-60/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-61/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-62/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-63/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-64/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-65/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-66/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-67/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-68/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-69/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-70/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-71/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-72/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-73/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-74/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-75/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-76/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-77/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-78/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-79/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-80/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-81/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-82/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-83/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-84/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-85/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-86/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-87/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-88/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-89/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-90/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-91/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-92/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-93/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-94/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-95/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-96/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-97/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-98/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-99/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n",
      "[SpawnPoolWorker-100/ERROR] 'ID flood wave shape'\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\experiment_runner.py\", line 89, in run_experiment\n",
      "    model.run_model(scenario, policy)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 390, in run_model\n",
      "    outputs = self.run_experiment(experiment)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\util\\ema_logging.py\", line 51, in wrapper\n",
      "    res = func(*args, **kwargs)\n",
      "  File \"C:\\Anaconda\\lib\\site-packages\\ema_workbench\\em_framework\\model.py\", line 442, in run_experiment\n",
      "    model_output = self.function(**experiment)\n",
      "  File \"C:\\Users\\Nick\\Documents\\Master EPA\\Q4\\EPA1361 - Model-based Decision-making\\final assignment\\dike_model_function.py\", line 158, in __call__\n",
      "    waveshape_id = node['ID flood wave shape']\n",
      "KeyError: 'ID flood wave shape'\n"
     ]
    }
   ],
   "source": [
    "with MultiprocessingEvaluator(model) as evaluator:\n",
    "    results = evaluator.optimize(nfe=250, searchover='levers',\n",
    "                                 epsilons=[0.1,]*len(model.outcomes))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "results"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
